development:
  adapter: mysql
  database: jobs_dev
  username: rails
  password: railsDev
  host: 127.0.0.1
  pool: 5

test:
  adapter: mysql
  database: jobs_test
  username: rails
  password: railsDev
  pool: 5
  host: 127.0.0.1
